### ISSUE TITLE
strange package.json

### ISSUE THREAD

**Issue by oprogramador** [mk-pmb/flatten-js#7]
Could you explain me this line?
https://github.com/mk-pmb/flatten-js/blob/9e94c8a06e9e9d5a2bc7e54e204feb52ad5783bc/package.json#L37

**Comment by mk-pmb** [comment]
Hi!
It's just a proprietary custom extra field I invented.
The part delimited by `-*-` helps some editors determine the file encoding. Usually I'd declare that with a UTF-8 Byte Order Mark, but npm fails to parse `package.json` if a BOM is present.
I use that line as a default bottom entry so I can add/remove properties above without the previously-last item's comma causing diff noise, because all items above do have a trailing comma.

**Comment by oprogramador** [comment]
OK, thanks
